# Generated by Django 3.1 on 2020-09-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MahasiswaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('nim', models.IntegerField()),
                ('kelas', models.CharField(max_length=250)),
                ('shift', models.CharField(choices=[('Reguler A', 'Reg A'), ('Reguler B', 'Reg B'), ('Reguler C', 'Reg C')], max_length=250)),
                ('jurusan', models.CharField(choices=[('Akutansi', 'Akutansi'), ('Biologi', 'Biologi'), ('Fisika', 'Fisika'), ('Ekonomi', 'Ekonomi'), ('Hukum', 'Hukum'), ('Ilmu Komputer', 'Ilmu Komputer'), ('Politik', 'Politik')], max_length=250)),
            ],
        ),
    ]
